- data/data.json
- rke/k8s_version_info.go
Rancher UI always picks the latest minor version based on the default k8s range. So we should only set major version and let it automatically pick the correct patch version based on min/max rancher info. 
https://github.com/rancher/rancher/issues/21598
> use major version for default k8s info

- rke/k8s_defaults.go
Since versions are now only major versions, validate panics. Validation logic was added with template changes 
https://github.com/rancher/rancher/pull/22261
> remove validate for rancher default versions

- data/data.json
- rke/k8s_defaults.go
- rke/templates/templates.go
- semver considers -rancher as a rc version, so removing it before matching range. 
- 1.16-beta < 1.16.0, add >=1.16-alpha for correct fetching of templates.
- while writing data, we also print template information for all k8s versions so user can validate their k8s version is getting the correct key and template. 
something like, 
```
"v1.16.0-beta.1-rancher1-1": {
"calico": "range=>=1.16.0-alpha key=calico-v1.16",
"canal": "range=>=1.16.0-alpha key=canal-v1.16",
"coreDNS": "range=>=1.8.0 <1.16.0 key=coredns-v1.8",
"flannel": "range=>=1.16.0-alpha key=flannel-v1.16",
"kubeDNS": "range=>=1.8.0 <1.16.0 key=kubedns-v1.8",
"metricsServer": "range=>=1.8.0 <1.16.0 key=metricsserver-v1.8",
"nginxIngress": "range=>=1.8.0 <1.16.0 key=nginxingress-v1.8",
"weave": "range=>=1.8.0 <1.16.0 …
```
> remove rancher suffix before testing range match

- data/data.json
- rke/k8s_rke_system_images.go
- rke/templates/templates.go
Reverting till we figure out why rancher/hyperkube doesn't work for Windows 1903 and k8s 1.16.1
> Revert "k8s 1.16.1"

- go.mod
- rke/k8s_defaults.go
old constraint: each plugin template must be present for all k8s versions
this is not very convenient if a new plugin is introduced only for new
versions, changed from error to warning
> relax template availability constraint

- data/data.json
- rke/k8s_version_info.go
This should be the same as https://github.com/rancher/kontainer-driver-metadata/pull/195
https://github.com/rancher/rancher/issues/26327
> [dev-v2.4] Set new min versions for introduced k8s versions

- data/data.json
- rke/k8s_version_info.go
This should be the same as https://github.com/rancher/kontainer-driver-metadata/pull/195
https://github.com/rancher/rancher/issues/26534
> [dev-v2.3] Set new min versions for introduced k8s versions

- data/data.json
- rke/k8s_defaults.go
- rke/k8s_rke_system_images.go
- rke/k8s_version_info.go
- Adds a check so we don't forget to check version restrictions for new k8s versions
- Adds versions that failed the new check
@deniseschannon Are these the new nodelocal backported versions so they need `vX.X.7`?
> Add versioninfo check for k8s versions

- rke/k8s_defaults.go
- rke/templates/templates.go
https://github.com/rancher/rancher/issues/25704
After adding nodelocal template (which is only active for newly introduced k8s versions), there would be errors shown in `go generate` because not all versions would have a nodelocal template configured. This introduces a new map to specify what version ranges should be used to check for missing templates. This removes the annoying and not actionable errors.
This PR also disables printing the whole JSON to stdout, and removes `generating data.json` from the beginning and adds `finished generating data.json` at the end.
> Add support for version checking for templates

- channels.yaml
- data/data.json
Bumps k3s v1.17.4 to v1.17.5
Adds in release v1.18.2
Tested on Rancher v2.4.3 and confirmed working correctly.
(Point Rancher v2.4.3 rke-metadata-config setting to my forked data.json to test, ensure k3s upgrades work correctly)
> Add new k3s releases [dev-v2.4]

- channels.yaml
- data/data.json
Removes v1.18.2 (https://github.com/rancher/kontainer-driver-metadata/pull/231)
Now, with these two PRs we are effectively only bumping k3s v1.17.4 to v1.17.5
> Bump k3s v1.17.4 to v1.17.5 stable

- data/data.json
- rke/cis_config.go
Since these two tests have been fixed in rancher for rke clusters, they now pass on out of the box rke clusters.
We can remove them from skipped set.
> Removing the tests from skipped set that have been fixed

- channels.yaml
- data/data.json
* Based on a slack conversation, we want v1.17.4 to stay in and target up to Rancher v2.4.2
* We want v1.17.5 in, but only for Rancher v2.4.3 and newer
* In the future, the maxChannelServerVersion would be changed to a lower version. This will become normal process.
> Add k3s v1.17.4 back in and limit Rancher version scope

- data/data.json
- rke/k8s_rke_system_images.go
- rke/k8s_version_info.go
Since 1.18 has not shipped yet, 1.18.2 will be directly replaced with 1.18.3.
Dependent on https://github.com/rancher/hyperkube/pull/110
> Bump k8s 1.18.2 to 1.18.3

- channels.yaml
- data/data.json
This should bring dev-v2.5 branch up to date with dev-v2.4 and release-v2.4
* Brings dev-v2.5 branch up to date with dev-v2.4 and release-v2.4
* This adds in the v1.17.5+k3s release to channels.yaml
* We limit the scope of Rancher versions accordingly
> Add k3s v1.17.5 and limit Rancher version scope

- channels.yaml
- data/data.json
* Bump to v1.17.5
* Add v1.18.2 for Rancher v2.4.4-rc1 min version
Related PR for dev-v2.5 branch: https://github.com/rancher/kontainer-driver-metadata/pull/255
> Bump k3s to v1.17.5 and add v1.18.2 entry for R v2.4.4-rc1 or higher

- data/data.json
- rke/cis_config.go
This is backward port for PR:  rancher/kontainer-driver-metadata#234
> [BackwardPort] Removing the CIS 1.5 tests from skipped set that have been fixed now

- channels.yaml
- data/data.json
* Bump the following k3s versions and increase min version for v1.18.x:
* v1.17.5 to v1.17.6
* v1.18.2 to v1.18.3
* Increase minChannelServerVersion for v1.18.x to v2.4.5-rc1 as we do not want v1.18.x to be an option in v2.4.4
> Bump k3s versions - dev-v2.4

- data/data.json
- rke/k8s_rke_system_images.go
- rke/k8s_service_options.go
- rke/k8s_version_info.go
address review comments from https://github.com/rancher/kontainer-driver-metadata/pull/288 and bump versions
> [dev-v2.4] new k8s versions - v1.16.11, v1.17.7

- data/data.json
- rke/k8s_rke_system_images.go
- rke/k8s_version_info.go
- Change `v1.18.3-rancher2-2` to `v1.18.4-rancher1-1`
- Add new hyperkube image `rancher/hyperkube:v1.18.4-rancher1`
- Generate data
> [2.4] New k8s version v1.18.4

- data/data.json
- rke/cis_config.go
This reverts commit 21a2ca9680f4903c3c931decb6cf8c640b883e53.
Even with the recent CIS 1.5 fixes, we should still skip these tests for a permissive scan since these two tests are too easy to break once user starts deploying workloads via Rancher to default project/default ns.
Hence these two tests will be skipped from a "permissive" profile. They will be run for a "hardened" profile.
> Revert "Removing the tests from skipped set that have been fixed" - We should still skip these tests for a permissive scan

- data/data.json
- rke/cis_config.go
This reverts commit 21a2ca9680f4903c3c931decb6cf8c640b883e53.
Backport PR for https://github.com/rancher/kontainer-driver-metadata/pull/284
> [Backport] Revert "Removing the tests from skipped set that have been fixed" - We should still skip these tests for a permissive scan

- data/data.json
- rke/cis_config.go
Adding one more PR to change the default CIS version on dev-v2.5
Copy of https://github.com/rancher/kontainer-driver-metadata/pull/286
> Change default CIS benchmark version

- channels.yaml
- data/data.json
Required for 7/15 security fixes
Bump k3s versions to v1.17.9+k3s1 and v1.18.6+k3s1
Go generate
Signed-off-by: David Nuzik <david.nuzik@rancher.com>
> Bump k3s versions to v1.17.9 and v1.18.6

- channels.yaml
- data/data.json
Backport PR for https://github.com/rancher/kontainer-driver-metadata/pull/317
Required for 7/15 security fixes
Bump k3s versions to v1.17.9+k3s1 and v1.18.6+k3s1
Go generate
Signed-off-by: David Nuzik <david.nuzik@rancher.com>
> [dev-v2.4] Bump k3s versions to v1.17.9 and v1.18.6

- data/data.json
- rke/k8s_rke_system_images.go
- rke/k8s_version_info.go
Since we have v1.16.13 with min v2.4.4, it seems inconsistent to have previous version at 2.4.5. It won't change anything for v2.4.4 because v1.16.13 is now the latest v1.16 patch version. Same logic for v1.17.6
> [dev-v2.4] update min version for v1.16.10-rancher2-2

- data/data.json
- rke/k8s_rke_system_images.go
- rke/k8s_version_info.go
New rke-tools version: `v0.1.61`
> Bump rke-tools to v0.1.61

- channels.yaml
- data/data.json
* Updates v1.17.9 to v1.17.11 and v1.18.6 to v1.18.8
* Note, v1.17.10 and v1.18.7 were skipped as upstream was having issues with these releases and taged new versions.
* go generate
> K3S - Update k3s v1.17 and v1.18 versions

- channels.yaml
- data/data.json
* Updates v1.17.9 to v1.17.11 and v1.18.6 to v1.18.8
* Note, v1.17.10 and v1.18.7 were skipped as upstream was having issues with these releases and taged new versions.
* go generate
> [dev-v2.4] Update k3s v1.17 and v1.18 versions

- data/data.json
- rke/k8s_rke_system_images.go
Update k8s v1.19.1 to include new ingress image: `rancher/nginx-ingress-controller:nginx-0.35.0-rancher1`
> [2.5] Update ingress version in K8S v1.19.1

- channels.yaml
- data/data.json
- Updates v1.17.11 to v1.17.12 and v1.18.8 to v1.18.9
- Add v1.19.2
- go generate
> K3S - Update k3s v1.17, v1.18 and add v1.19

- channels.yaml
- data/data.json
- Bump k3s versions to v1.17.12+k3s1 and v1.18.8+k3s1
- Add k3s version v1.19.2
- Change max version to v2.5.99 
- Go generate
> [dev-2.4] Update k3s  v1.17.12, v1.18.9 and add v1.19.2

- channels-rke2.yaml
- data/data.json
This pr updates rke2 version to v1.18.9+rke2 
issue : https://github.com/rancher/rke2/issues/383
> Bump RKE2 version to v1.18.9+rke2

- channels-rke2.yaml
- data/data.json
This pr updates rke2 release tag to `v1.18.9+rke2r1` instead of `v1.18.9+rke2`
related issue : https://github.com/rancher/rke2/issues/383
> update rke2 release tag

- channels.yaml
- data/data.json
This pr updates the k3s versions for Oct 30 releases, (+k3s2) releases
issue: https://github.com/rancher/k3s/issues/2460
>  bump k3s versions 10/30/20 Patch Releases

- channels.yaml
- data/data.json
This pr updates the k3s versions for Oct 30 releases, (+k3s2) releases
issue: rancher/k3s#2460
> [2.4] bump k3s versions 10/30/20 Patch Releases

- channels-rke2.yaml
- data/data.json
This pr updates rke2 version to v1.18.11+rke2r1
> bump rke2 version

- channels.yaml
- data/data.json
upstream is skipping v1.18.11, this pr updates k3s version to v1.18.12
> [dev-2.4]Bump k3s 1.18

- channels.yaml
- data/data.json
upstream is skipping v1.18.11, this pr updates k3s version to v1.18.12
> [dev-2.5]Bump k3s 1.18

- channels.yaml
- data/data.json
Bump v1.17.14+k3s1 to v1.17.14+k3s2 because before we found this severe bug in kine we already had v1.17.14+k3s1 out. Now we need a +k3s2 of this which will contain the fix.
Leave v1.18.12+k3s1 as it is because it was already rev'ed in prior PRs and not yet released before the severe kine fix.
Bump v1.19.4+k3s1 to v1.19.3+k3s3 actually because we are having build issues with v1.19.4+k3s2 and because we need this urgent kine fix, we will get a v1.19.3+k3s3 release out because we cannot wait to fix this build issue, thus we need a +k3s3 release of v1.19.3
> [2.5] Bump k3s version for urgent release tags 

- channels.yaml
- data/data.json
Bump v1.17.14+k3s1 to v1.17.14+k3s2 because before we found this severe bug in kine we already had v1.17.14+k3s1 out. Now we need a +k3s2 of this which will contain the fix.
Leave v1.18.12+k3s1 as it is because it was already rev'ed in prior PRs and not yet released before the severe kine fix.
Bump v1.19.4+k3s1 to v1.19.3+k3s3 actually because we are having build issues with v1.19.4+k3s2 and because we need this urgent kine fix, we will get a v1.19.3+k3s3 release out because we cannot wait to fix this build issue, thus we need a +k3s3 release of v1.19.3
> [2.4] Bump k3s version for urgent release tags

- channels-rke2.yaml
- data/data.json
Decrease RKE2 version from v1.18.11+rke2r1 to v1.18.10+rke2r1 because we originally planned to release RKE2 before a KDM release. Now that we need to urgently get K3s releases out to fix a bug in Kine we will release KDM before RKE2 is ready. (RKE2 is not affected by this bug as it does not leverage kine)
> Revert rke2 version

- channels-rke2.yaml
- channels.yaml
- data/data.json
This pr updates k3s and rke2 versions in kdm for https://github.com/k3s-io/k3s/issues/2618 and https://github.com/rancher/rke2/issues/557
> [channelserver] bump k3s and rke2 versions 

- channels-rke2.yaml
- data/data.json
this pr bumps rke2 version to v1.19.5+rke2r1
issue: https://github.com/rancher/rke2/issues/610
> [dev-2.5] Bump rke2 v1.19.5

- channels-rke2.yaml
- data/data.json
this pr adds support for rke2 v1.18 and 1.19 to be available for upgrades in rancher
> Add availability for rke2 v1.19 and v1.18

- channels.yaml
- data/data.json
this pr bumps k3s versions v1.17.17 , v1.18.15 ,v1.19.7 and v1.20.2
issue : https://github.com/k3s-io/k3s/issues/2795
> [dev-2.5] K3s jan 13th

- channels-rke2.yaml
- data/data.json
this pr bumps rke2 versions 1.18.5 and 1.19.7
issue : https://github.com/rancher/rke2/issues/657
> [dev-2.5] Rke2 jan 13th
