data/data.json
rke/k8s_rke_system_images.go
rke/k8s_version_info.go
rke/k8s_windows_service_options.go

- Windows service options:
- HyperVContainer, WindowsGMSA only works on kubelet
- WinOverlay, WinDSR should not declares together
- Windows images:
- Update rancher/hyperkube
- Update rancher/rke-tools
**Todo:**
+ [ ] rancher/rke-tools: https://github.com/rancher/rke-tools/pull/74 , https://github.com/rancher/rke-tools/pull/75
+ [ ] rancher/hyperkube: https://github.com/rancher/hyperkube/pull/60 , https://github.com/rancher/hyperkube/pull/61 , https://github.com/rancher/hyperkube/pull/62

Adjust windows arguments

---

data/data.json
rke/k8s_version_info.go

https://github.com/rancher/rancher/issues/22965

k8s 1.16 as default for 2.3.2

---

data/data.json
rke/k8s_version_info.go

https://github.com/rancher/rancher/issues/23689

default k8s version 1.15.x

---

data/data.json
rke/k8s_service_options.go

https://github.com/rancher/rancher/issues/24641
https://github.com/rancher/rancher/issues/24642

Enable v2 API for etcd 3.4 (k8s 1.17)

---

data/data.json
rke/k8s_windows_service_options.go

https://github.com/rancher/rancher/issues/24830

V117 windows support

---

data/data.json
rke/cis_config.go

https://github.com/rancher/rancher/issues/24987

add options for cis 1.5

---

data/data.json
rke/k8s_service_options.go

[dev-v2.3] Add etcd options for new k8s versions

---

channels.yaml
data/data.json

**Issue:**
https://github.com/rancher/rancher/issues/26011

Include rc

---

channels.yaml
data/data.json

**Issue:**
https://github.com/rancher/rancher/issues/26200

Add rc2+k3s1

---

channels.yaml
data/data.json

Addresses https://github.com/rancher/rancher/issues/25750
Wait to merge until k3s v1.17.4-rc2+k3s1

Update data.json for k3s 1.17.4

---

data/data.json
rke/k8s_version_info.go

https://github.com/rancher/rancher/issues/26327

[2.3] rancher min version 2.3.6: v1.15.11-rancher1-2, v1.16.8-rancher1-2, v1.17.4-rancher1-2

---

data/data.json
rke/k8s_version_info.go

https://github.com/rancher/rancher/issues/26327

rancher min version 2.3.6: v1.15.11-rancher1-2, v1.16.8-rancher1-2, v1.17.4-rancher1-2

---

data/data.json
rke/k8s_version_info.go

https://github.com/rancher/rancher/issues/26327

[dev-v2.5] Set new min versions for introduced k8s versions

---

data/data.json
rke/k8s_defaults.go
rke/k8s_rke_system_images.go
rke/k8s_version_info.go

Backport of https://github.com/rancher/kontainer-driver-metadata/pull/207

[dev-v2.4] Add versioninfo check for k8s versions

---

rke/k8s_defaults.go
rke/templates/templates.go

Backport of https://github.com/rancher/kontainer-driver-metadata/pull/208
https://github.com/rancher/rancher/issues/25704

[dev-v2.4] Add support for version checking for templates

---

rke/k8s_defaults.go
rke/templates/templates.go

Backport of https://github.com/rancher/kontainer-driver-metadata/pull/208
https://github.com/rancher/rancher/issues/25704

[dev-v2.3] Add support for version checking for templates

---

data/data.json
rke/k8s_version_info.go

https://github.com/rancher/rancher/issues/26763

Change rancherMinVersion for 1.15 nodelocal

---

channels.yaml
data/data.json

[dev-v2.5] Bump k3s versions

---

data/data.json
rke/k8s_rke_system_images.go
rke/k8s_service_options.go
rke/k8s_version_info.go

Original PR:
- rancher/kontainer-driver-metadata#287
2.4 Backport PR:
- rancher/kontainer-driver-metadata#292

[2.3] Backport new k8s versions / image tags for flannel and windows

---

data/data.json
rke/k8s_version_info.go

Issue:
- rancher/rancher#27577

[2.3] Fix version info for v1.15.12-rancher2-3

---

channels.yaml
data/data.json

* Bump v1.17.6+k3s1 to v1.17.7+k3s1
* Bump v1.18.3+k3s1 to v1.18.4+k3s1

Bump k3s versions

---

data/data.json
rke/k8s_rke_system_images.go
rke/k8s_service_options.go
rke/k8s_version_info.go

Addressing the comments here:
- rancher/kontainer-driver-metadata#300
Also doing version bumps since new k8s patch versions have been released

[2.3] fixes / new k8s versions v1.16.11, v1.17.7

---

channels.yaml
data/data.json

Pick and backport for dev-v2.4 (k3s versions)

[dev-v2.4] Bump k3s versions

---

rke/k8s_rke_system_images.go

Addressing this comment:
- https://github.com/rancher/kontainer-driver-metadata/pull/300/files#r441510261

[2.3] Fix comment for version tracking

---

data/data.json
rke/k8s_service_options.go

- Add service options for `v1.16.10-rancher2-2`

[2.5] v1.16.10-rancher2-2 service options

---

data/data.json
rke/cis_config.go

https://github.com/rancher/rancher/issues/27446

Change default CIS benchmark version to CIS 1.5

---

data/data.json
rke/k8s_rke_system_images.go
rke/k8s_version_info.go

- update templates
- change defaults
- generate data

[2.4] Update templates for v1.16.12-rancher1-1, v1.17.8-rancher1-1, and v1.18.5-rancher1-1

---

data/data.json
rke/k8s_rke_system_images.go
rke/k8s_version_info.go

Reverts rancher/kontainer-driver-metadata#313

Revert "[2.4] Update templates for v1.16.12-rancher1-1, v1.17.8-rancher1-1, and v1.18.5-rancher1-1"

---

data/data.json
rke/k8s_rke_system_images.go
rke/k8s_service_options.go
rke/k8s_version_info.go

v1.16.13, v1.17.9 could come from v2.3.8+'s upgraded versions 
v1.18.6 needs to be available v2.4.5+

[dev-v2.4] v1.16.13, v1.17.9, v1.18.6

---

data/data.json
rke/cis_config.go

BackwardPort of PR https://github.com/rancher/kontainer-driver-metadata/pull/286

[2.4] Change default CIS benchmark version to CIS 1.5

---

channels-rke2.yaml
data/data.json

this pr update rke2 release version to `v1.18.4-alpha19+rke2`

Update rke2 release

---

channels.yaml
data/data.json

https://github.com/rancher/kontainer-driver-metadata/pull/343

[release-v2.4] k3s v1.17.11 and v1.18.8

---

data/data.json
rke/k8s_version_info.go

https://github.com/rancher/rancher/issues/28828

update 1.15's max version to 2.4.x

---

channels-rke2.yaml
data/data.json

- Update version to v1.18.8-beta19+rke2
- go generate

Rke2: Update version to v1.18.8-beta19+rke2

---

channels-rke2.yaml
data/data.json

This pr updates rke2 version to v1.18.10+rke2r1 
issue : https://github.com/rancher/rke2/issues/484

Bump rke2 v1.18.10

---

data/data.json
rke/k8s_rke_system_images.go

https://github.com/rancher/rancher/issues/29881
see https://github.com/rancher/kontainer-driver-metadata/pull/391

[dev-v2.5] update ingress for v1.16.15-rancher1-3

---

data/data.json
rke/k8s_service_options.go

https://github.com/rancher/kontainer-driver-metadata/blob/release-v2.4/rke/k8s_service_options.go#L128 for reference

[dev-v2.5] add service options for v1.16.15-rancher1-2

---

channels.yaml
data/data.json

This pr updates k3s versions to v1.17.14,v1.18.11 and v1.19.4

[dev-2.5]11/11/20 k3s patch releases

---

channels.yaml
data/data.json

This pr updates k3s versions to v1.17.14,v1.18.11 and v1.19.4

[dev-2.4]11/11/20 k3s patch releases 

---

channels-rke2.yaml
data/data.json

issue : https://github.com/rancher/rke2/issues/509

Bump rke2 version v1.18.12+rke2r1

---

channels.yaml
data/data.json

This pr updates k3s versions in kdm for k3s-io/k3s#2618

[dev-v2.4] bump k3s versions 

---

channels.yaml
data/data.json

Issue : https://github.com/k3s-io/k3s/issues/2670

[dev-2.4]K3s December 9, 2020 Patch Releases

---

channels.yaml
data/data.json

issue : https://github.com/k3s-io/k3s/issues/2670

[dev-2.5] K3s December 9, 2020 Patch Releases

---

channels-rke2.yaml
data/data.json

issue: https://github.com/rancher/rke2/issues/583

[dev-2.5]bump rke2 version v1.18.13+rke2r1

---

channels.yaml
data/data.json

release will be going out later tonight

update to k8s v1.19.5+k3s2

---

channels.yaml
data/data.json

this pr bumps k3s versions v1.17.17 , v1.18.15 ,v1.19.7
issue :  k3s-io/k3s#2795

[dev-2.4] K3s jan 13th

---

data/data.json
rke/k8s_rke_system_images.go
rke/k8s_version_info.go

Preparing this for upcoming v1.17.17 k8s release

[dev-v2.3] Add v1.17.17-rancher1-1
